server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      
logging:
  level:
    root: info
    org.springframework: info
    org.springframework.web: info
      
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: //mysql uri
    username: // username
    password: // userpw

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
   
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: client-id
            client-secret: secret
            scope:
              - email
              - profile
           
          naver:
            client-id: client-id
            client-secret: secret
            client-name: Naver
            scope:
              - name
              - email
            authorization-grant-type: authorization_code
            redirect-uri: redirect-uri
            
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
                
            
          